### ISSUE TITLE
Proposition for chapitre8_exercice1.js

### ISSUE THREAD

**Issue by Bk201Freelance** [thejsway/thejsway_fr-code#27]
Hello,

First thing first, thank you for your work and your course on JavaScript.

I have a suggestion for the "chapitre8_exercice1.js"

`function compterVoyelles(mot){
  const voyelles = ["a","e","i","o","u","y"];
  let nombreVoyelles = 0;
  for(i=0;i<voyelles.length;i++){
    for(const lettre of mot.toLowerCase()){
      if(lettre === voyelles[i]){
        nombreVoyelles++;
      };
    };
  };
  return nombreVoyelles;
};

console.log(compterVoyelles("RadAr")); // 2
console.log(compterVoyelles("Tic et Tac")); // 3
console.log(compterVoyelles("Oasis Oasis Oh")); // 7
`

Hope it's a good solution.

Best regards

**Comment by bpesquet** [comment]
Hi,
Thanks for your solution. It's not better because more loop iterations are needed, but it works fine.
