### ISSUE TITLE
Proposition valable pour heure.js

### ISSUE THREAD

**Issue by olivier1208** [thejsway/thejsway_fr-code#6]
Pour moi ce code a marché ;)
/\* Etudiant PP OC*/
var heures = Number(prompt("Saisissez ici l'heure (entre 0 et 23)"));
var minutes = Number(prompt("Saisissez ici les minutes (entre 0 et 59)"));
var seconds = Number(prompt("Saisissez ici les secondes (entre 0 et 59)"));

if ((heures > 0 && heures < 23) && (minutes > 0 && minutes < 59) && (seconds > 0 && seconds < 59)) {

```
seconds++;
console.log("Le résultat est " + heures + " Heures " + minutes + " minutes et  " + seconds + " secondes");
```

} else if (heures === 23 && minutes === 59 && seconds === 59) {
    heures = "00";
    minutes = "00";
    seconds = "00";
    console.log("Le résultat est " + heures + " Heures " + minutes + " minutes et " + seconds + " secondes (minuit)");
} else if (minutes === 59 && seconds === 59) {
    minutes = "00";
    seconds = "00";
    heures++;
    console.log("Le résultat est " + heures + " Heures " + minutes + " minutes et  " + seconds + " secondes");
} else if (seconds === 59) {
    seconds = 0;
    minutes++;
    console.log("Le résultat est " + heures + " Heures " + minutes + " minutes et  " + seconds + " secondes");
} else {
    console.log("Erreur de saisie")
}

**Comment by bpesquet** [comment]
Oui mais vous dupliquez le code d'affichage du message, ce qui compliquera son changement ou sa traduction dans une autre langue.

**Comment by olivier1208** [comment]
Ha Merci Beaucoup !!
Bonne journée

**Comment by olivier1208** [comment]
En effet, je n'avais compris du cours, que nous pouvions intégrer plusieurs
if dans la même expression.
Merci !

Le 7 juin 2016 à 13:23, Baptiste Pesquet notifications@github.com a écrit
:
